Import toplevel module before submodules
Travis CI builds for Python 2.* are failing with an import error.

    ======================================================================
    ERROR: Failure: ImportError (No module named exceptions)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/miniconda/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
        addr.filename, addr.module)
      File "/home/travis/miniconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
        return self.importFromDir(dir_path, fqname)
      File "/home/travis/miniconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
        mod = load_module(part_fqname, fh, filename, desc)
      File "/home/travis/build/ChrisCummins/srtime/tests/test_process.py", line 3, in <module>
        from srtime.process import Process
      File "/home/travis/build/ChrisCummins/srtime/srtime/__init__.py", line 5, in <module>
        from srtime.argparse import ArgumentParser
      File "/home/travis/build/ChrisCummins/srtime/srtime/srtime.py", line 3, in <module>
        from srtime.exceptions import InvalidParameterException
    ImportError: No module named exceptions

I believe this is caused by attempting to import a submodule before
importing the top level. This patch addresses that by ensuring that any
importing of srtime.* modules is first preceded by an import of srtime.