Drop Python 2.6 from Travis CI builds
One or more of the dependent packages is unsupported by Python 2.6,
causing builds to fail at the install stage:

    $ conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
    Fetching package metadata: ..
    Solving package specifications: ..
    Error: Unsatisfiable package specifications.
    Generating hint:
    [      COMPLETE      ] |##################################################| 100%
    Hint: the following combinations of packages create a conflict with the
    remaining packages:
      -
      - python 2.6*
    The command "conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels" failed and exited with 1 during .
    Your build has been stopped.

This effectively means dropping support for Python 2.6. So long, and
thanks for all the compatibility issues.