test: Import toplevel module before submodules
This is a continuation of commit:

commit c10b11ea8b520a49a15a5932051240dec781326c
Author: Chris Cummins <chrisc.101@gmail.com>
Date:   Mon Nov 17 12:16:23 2014 +0000

    Import toplevel module before submodules

In which I attempted to address CI test errors for Python 2.7:

    ======================================================================
    ERROR: Failure: ImportError (No module named exceptions)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/miniconda/lib/python2.7/site-packages/nose/loader.p
        addr.filename, addr.module)
      File "/home/travis/miniconda/lib/python2.7/site-packages/nose/importer
        return self.importFromDir(dir_path, fqname)
      File "/home/travis/miniconda/lib/python2.7/site-packages/nose/importer
        mod = load_module(part_fqname, fh, filename, desc)
      File "/home/travis/build/ChrisCummins/srtime/tests/test_process.py", l
        from srtime.process import Process
      File "/home/travis/build/ChrisCummins/srtime/srtime/__init__.py", line
        from srtime.argparse import ArgumentParser
      File "/home/travis/build/ChrisCummins/srtime/srtime/srtime.py", line 3
        from srtime.exceptions import InvalidParameterException
    ImportError: No module named exceptions

In the referenced commit, I forgot to fix the test files.